feat: add support for GCP bootstrap
Signed-off-by: Ales Verbic <verbotenj@blinklabs.io>

diff --git a/bin/bootstrap-cloud b/bin/bootstrap-cloud
--- a/bin/bootstrap-cloud
+++ b/bin/bootstrap-cloud
@@ -3,6 +3,21 @@
 # This script is designed to help someone bootstrap terraform and requires the
 # user already has AWS credentials and Terraform installed
 
+# NOTE: we use the gcloud command line tool to verify you have access configured
+check_gcp_prerequisites() {
+  gcloud config get project >/dev/null 2>&1
+  if [[ $? -ne 0 ]]; then
+    echo "You must configure your local 'gcloud' client before using this tool"
+    echo "Run 'gcloud auth login'"
+    echo 'Run 'gcloud projects list' to see your projects'
+    echo "Run 'gcloud config set project <project-id>'"
+    echo "Run 'gcloud auth application-default login'"
+    echo "Run 'bin/bootstrap-cloud' to continue"
+    exit 1
+  fi
+  return 0
+}
+
 # NOTE: we use the aws command line tool to verify you have access configured
 check_aws_prerequisites() {
   aws sts get-caller-identity 2>&1 >/dev/null
@@ -10,7 +25,9 @@ check_aws_prerequisites() {
     echo "You must configure your local 'aws' client before using this tool"
     exit 1
   fi
+}
 
+check_terraform_prerequisites() {
   local __tfver=$(terraform version | sed 's/^.* v//' 2>/dev/null)
   if [[ $? -eq 0 ]]; then
     local __tmp=( ${__tfver//./ } )
@@ -44,16 +61,19 @@ if test -e ${__root}/config.yaml; then
   [[ -z ${__bucket} ]] && unset __bucket
   [[ -z ${__region} ]] && unset __region
 else
+  echo "No config.yaml found, using defaults"
   __cloud=k3d
 fi
 
 echo bootstrapping terraform for ${__cloud}
 
-if [[ ${__cloud} == aws ]]; then
+case ${__cloud} in
+  aws)
   check_aws_prerequisites
+  check_terraform_prerequisites
 
   set -e
-  cd ${__root}/bootstrap
+  cd ${__root}/bootstrap/aws-terraform
   if [[ -z ${__bucket} ]] && [[ -z ${__region} ]]; then
     terraform init
     terraform validate
@@ -192,9 +212,99 @@ if [[ ${__cloud} == aws ]]; then
 	-e "s#some-context#aws-${__name}#" \
         env.auto.tfvars.example > env.auto.tfvars
   fi
+  ;;
+  gcp)
+    check_gcp_prerequisites
+    check_terraform_prerequisites
+    
+    # Config file has to exist at this point
+    if [[ ! -e ${__root}/config.yaml ]]; then
+      echo "config.yaml not found, exiting..."; exit 1
+    fi
+    # Get the project ID
+    __project_id=$(grep ^terraform_project_id: ${__root}/config.yaml | awk '{print $2}')
+    if [[ -z ${__project_id} ]]; then
+      echo "terraform_project_id not found in config.yaml, exiting..." 
+      echo "Hint: run 'gcloud projects list' to see your projects"
+      exit 1
+    fi
+    
+    set -e
+    cd ${__root}/bootstrap/gcp-terraform
+    terraform init
+    terraform validate
+    set +e
+    terraform plan -detailed-exitcode -input=false  
+    
+    __ret=$?
+    case ${__ret} in
+      2) terraform apply -auto-approve ;;
+      0) echo terraform apply skipped with no changes ;;
+      *) echo terraform plan result ${__ret} && exit ${__ret} ;;
+    esac
+    __ret=$?
+    case ${__ret} in
+      0) echo terraform apply successful ;;
+      *) echo terraform apply result ${__ret} && exit ${__ret} ;;
+    esac
 
-else # k3d
+    set -e
+    __bucket=$(terraform output -raw terraform_state_bucket)
+    __kmskey=$(terraform output -raw terraform_state_crypto_key)
+    __project_id=$(terraform output -raw terraform_project_id)
+    if [[ ${__bucket} =~ bucket-tfstate ]]; then
+      echo Terraform state bucket: ${__bucket}
+    else
+      echo Could not detect state bucket && exit 1
+    fi
+    if [[ ${__kmskey} =~ terraform-state-bucket ]]; then
+      echo Terraform state KMS key: ${__kmskey}
+    else
+      echo Could not detect state KMS key && exit 1
+    fi
+    
+    set +e
+    # configure bootstrap backend
+    __configure_bootstrap_backend=false
+    if [[ ! -e backend.tf ]]; then
+      __configure_bootstrap_backend=true
+    elif [[ $(grep -o BUCKET_NAME backend.tf 2>/dev/null) == BUCKET_NAME ]]; then
+      __configure_bootstrap_backend=true
+    elif [[ $(grep -o KMS_ENCRYPTION_KEY backend.tf 2>/dev/null) == KMS_ENCRYPTION_KEY ]]; then
+      __configure_bootstrap_backend=true
+    fi
+    set -e
+    if [[ ${__configure_bootstrap_backend} == true ]]; then
+      echo configuring bootstrap backend
+      sed -e "s#BUCKET_NAME#${__bucket}#" \
+          -e "s#KMS_ENCRYPTION_KEY#${__kmskey}#" \
+          backend-gcp.tf.example > backend.tf
+      terraform init -migrate-state -force-copy
+    fi
 
+    set +e
+    cd ${__root}/bootstrap/gcp-terraform
+    # configure projects backend
+    __configure_projects_backend=false
+    if [[ ! -e backend.tf ]]; then
+      __configure_projects_backend=true
+    elif [[ $(grep -o BUCKET_NAME backend.tf 2>/dev/null) == BUCKET_NAME ]]; then
+      __configure_projects_backend=true
+    elif [[ $(grep -o KMS_ENCRYPTION_KEY backend.tf 2>/dev/null) == KMS_ENCRYPTION_KEY ]]; then
+      __configure_projects_backend=true
+    fi
+    set -e
+    if [[ ${__configure_projects_backend} == true ]]; then
+      echo configuring projects backend
+      sed -e "s#BUCKET_NAME#${__bucket}#" \
+          -e "s#KMS_ENCRYPTION_KEY#${__kmskey}#" \
+          backend-gcp.tf.example > backend.tf
+      terraform init -migrate-state -force-copy
+    fi
+    echo "Initial Bootstrap Complete"
+    #TODO: Add the rest of the stages
+    ;;
+k3d)
   cd ${__root}/bootstrap
   if test -e ${__root}/config.yaml; then
     __name=$(grep ^cluster_name: ${__root}/config.yaml | awk '{print $2}')
@@ -228,4 +338,6 @@ else # k3d
 	-e "s#some-context#k3d-${__name}#" \
         env.auto.tfvars.example > env.auto.tfvars
   fi
-fi
+  ;;
+*) echo "Invalid choice for the cloud_provider. Selected ${__cloud} is not supported" && exit 1 ;;
+esac
